print("Exponential program")
print("----------------------")
x=int(input("Enter x value:"))
y=int(input("Enter y value:"))
z=int(input("Enter z value:"))
print("Result")
p=(x*x)+(y*y)+(z*z)
print("p=",p)
q=(x*x*x)+((y*y)*z)+(z*z*z)
print("q=",q)
R=(x*x)*y+(y*y)*z+(z*z)*x+10
print("R=",R)
s=(x*x*x*y*y*z)+2*(x*y*z)+(x*y*z)
print("s=",s)
